// packages/kaguya-app/src/ui/Layout.svelte
<!--
  SPDX-License-Identifier: MPL-2.0

  Svelte port of Layout.tsx. Not yet mounted at runtime —
  Layout.tsx remains the live root layout until M1 mount swap.

  Compose-modal a11y (mio's pin):
  1. focus trap via `use:focusTrap` action (src/ui/focusTrap.ts)
  2. ESC key close: window keydown listener inside $effect
  3. role="dialog" aria-modal="true" aria-labelledby on modal root
  4. scroll lock: document.body.style.overflow = 'hidden' while open
-->

<script lang="ts">
  import type { Snippet } from 'svelte'
  import Link from './Link.svelte'
  import { navigate, currentPath } from './svelteRouter'
  import { instanceName } from '../domain/auth/appState'
  import { unreadCount, inboxCount, initInbox } from '../domain/notification/notificationStore'
  import { initFilteredTimeline } from '../domain/timeline/filteredTimelineStore'
  import { init as themeInit, toggle as themeToggle, isDark, currentTheme } from './themeStore'
  import {
    init as preferencesInit,
    quietMode,
    isQuiet as isQuietSignal,
    isQuietHoursActive,
    setQuietMode,
    toggleQuietMode,
  } from './preferencesStore'
  import { init as mediaProxyInit } from '../infra/mediaProxy'
  import { init as i18nInit, t, currentLocale } from '../infra/i18n'
  import AccountSwitcher from '../domain/account/AccountSwitcher.svelte'
  import PostForm from './PostForm.svelte'
  import { svelteSignal } from './svelteSignal.svelte'
  import { focusTrap } from './focusTrap'
  import { onMount } from 'svelte'

  type Props = { children: Snippet }
  let { children }: Props = $props()

  const pathR = svelteSignal(currentPath)
  const instNameR = svelteSignal(instanceName)
  const notifCountR = svelteSignal(unreadCount)
  const inboxUnreadR = svelteSignal(inboxCount)
  const themeR = svelteSignal(currentTheme)
  const localeR = svelteSignal(currentLocale)
  const quietModeR = svelteSignal(quietMode)
  const isQuietR = svelteSignal(isQuietSignal)
  const quietHoursActiveR = svelteSignal(isQuietHoursActive)

  let showCompose = $state(false)

  onMount(() => {
    i18nInit()
    themeInit()
    preferencesInit()
    mediaProxyInit()
    initInbox()
    initFilteredTimeline()
  })

  // Drive isDark() through themeR so it re-evaluates on theme switch.
  const darkMode = $derived((themeR.value, isDark()))

  const location = $derived(pathR.value)
  const notifCount = $derived(notifCountR.value)
  const inboxUnread = $derived(inboxUnreadR.value)
  const instName = $derived(instNameR.value)
  const manualQuiet = $derived(quietModeR.value)
  const quietHoursActive = $derived(quietHoursActiveR.value)
  const isQuiet = $derived(isQuietR.value)

  function isActive(path: string): boolean {
    return location === path
  }

  function handleBack() {
    if (history.length > 1) history.back()
    else navigate('/')
  }

  function scrollMainToTop() {
    const main = document.querySelector<HTMLElement>('.layout-main > main')
    if (main) main.scrollTo({ top: 0, behavior: 'smooth' })
    else window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  function handleHomeClick() {
    if (location === '/') scrollMainToTop()
    else navigate('/')
  }

  const isRootPage = $derived(
    location === '/' ||
      location === '/notifications' ||
      location === '/inbox' ||
      location === '/timeline-inbox' ||
      location === '/settings' ||
      location === '/performance' ||
      location === '/miauth-callback' ||
      location.startsWith('/oauth-callback'),
  )

  const L = $derived((localeR.value, {
    sideNav: t('nav.side_navigation'),
    bottomNav: t('nav.bottom_navigation'),
    home: t('nav.home'),
    inbox: t('nav.inbox'),
    notifications: t('nav.notifications'),
    settings: t('nav.settings'),
    back: t('nav.back'),
    appTitle: t('app.title'),
    tagline: t('app.tagline'),
    composeTitle: t('compose.title'),
    actionClose: t('action.close'),
    quietOn: t('quiet_mode.on'),
    quietOff: t('quiet_mode.off'),
    quietHoursActive: t('quiet_mode.hours_active'),
    quietManualActive: t('quiet_mode.manual_active'),
    quietResume: t('quiet_mode.resume'),
    themeToLight: t('theme.switch_to_light'),
    themeToDark: t('theme.switch_to_dark'),
  }))

  // ESC close + body scroll lock for compose modal.
  $effect(() => {
    if (!showCompose) return
    const prevOverflow = document.body.style.overflow
    document.body.style.overflow = 'hidden'
    function onKey(e: KeyboardEvent) {
      if (e.key === 'Escape') {
        e.stopPropagation()
        showCompose = false
      }
    }
    window.addEventListener('keydown', onKey)
    return () => {
      window.removeEventListener('keydown', onKey)
      document.body.style.overflow = prevOverflow
    }
  })

  function closeComposeOnBackdrop(e: MouseEvent) {
    if (e.target === e.currentTarget) showCompose = false
  }
</script>

<div class="layout">
  <nav class="left-sidebar" aria-label={L.sideNav}>
    <Link href="/" class="sidebar-logo">
      <div class="sidebar-logo-icon">🌿</div>
    </Link>
    <div class="sidebar-nav-items">
      <button
        class="sidebar-nav-btn {isActive('/') ? 'active' : ''}"
        onclick={handleHomeClick}
        title={L.home}
        aria-label={L.home}
        type="button"
      >
        <iconify-icon icon="tabler:home"></iconify-icon>
      </button>
      <button
        class="sidebar-nav-btn {isActive('/inbox') ? 'active' : ''}"
        onclick={() => navigate('/inbox')}
        title={L.inbox}
        aria-label={L.inbox}
        type="button"
      >
        <iconify-icon icon="tabler:inbox"></iconify-icon>
        {#if inboxUnread > 0}
          <span class="sidebar-notification-badge">{inboxUnread > 99 ? '99+' : inboxUnread}</span>
        {/if}
      </button>
      <button
        class="sidebar-nav-btn {isActive('/notifications') ? 'active' : ''}"
        onclick={() => navigate('/notifications')}
        title={L.notifications}
        aria-label={L.notifications}
        type="button"
      >
        <iconify-icon icon="tabler:bell"></iconify-icon>
        {#if notifCount > 0}
          <span class="sidebar-notification-badge">{notifCount > 99 ? '99+' : notifCount}</span>
        {/if}
      </button>
    </div>
    <div class="sidebar-bottom">
      <button
        class="sidebar-nav-btn"
        onclick={toggleQuietMode}
        title={manualQuiet ? L.quietOff : L.quietOn}
        aria-label={manualQuiet ? L.quietOff : L.quietOn}
        aria-pressed={isQuiet}
        type="button"
      >
        <iconify-icon icon={isQuiet ? 'tabler:player-play' : 'tabler:player-pause'}></iconify-icon>
      </button>
      <button
        class="sidebar-nav-btn theme-toggle-sidebar"
        onclick={themeToggle}
        title={darkMode ? L.themeToLight : L.themeToDark}
        aria-label={darkMode ? L.themeToLight : L.themeToDark}
        type="button"
      >
        <iconify-icon icon={darkMode ? 'tabler:sun' : 'tabler:moon'}></iconify-icon>
      </button>
      <button
        class="sidebar-nav-btn {isActive('/settings') ? 'active' : ''}"
        onclick={() => navigate('/settings')}
        title={L.settings}
        aria-label={L.settings}
        type="button"
      >
        <iconify-icon icon="tabler:settings"></iconify-icon>
      </button>
    </div>
  </nav>

  <div class="layout-main">
    <header class="container-fluid">
      <nav>
        <ul>
          <li>
            {#if !isRootPage}
              <button class="header-back-btn" onclick={handleBack} title={L.back} aria-label={L.back} type="button">
                <iconify-icon icon="tabler:arrow-left"></iconify-icon>
              </button>
            {/if}
            <Link href="/" class="header-logo-link" onclick={() => { if (location === '/') scrollMainToTop() }}>
              <span class="header-leaf-icon">🌿</span>
            </Link>
            <strong class="app-title">{L.appTitle}</strong>
            {#if instName}
              <small class="instance-badge">{instName}</small>
            {/if}
          </li>
        </ul>
        <ul>
          <li>
            <Link
              href="/"
              class="header-nav-link {isActive('/') ? 'active' : ''}"
              onclick={() => { if (location === '/') scrollMainToTop() }}
            >
              {L.home}
            </Link>
          </li>
          <li>
            <Link
              href="/notifications"
              class="notification-bell header-nav-link {isActive('/notifications') ? 'active' : ''}"
            >
              🔔
              {#if notifCount > 0}
                <span class="notification-badge">{notifCount > 99 ? '99+' : notifCount}</span>
              {/if}
            </Link>
          </li>
        </ul>
        <ul>
          <li>
            <button
              class="theme-toggle-btn"
              onclick={themeToggle}
              title={darkMode ? L.themeToLight : L.themeToDark}
              aria-label={darkMode ? L.themeToLight : L.themeToDark}
              type="button"
            >
              <iconify-icon icon={darkMode ? 'tabler:sun' : 'tabler:moon'}></iconify-icon>
            </button>
          </li>
          <li><AccountSwitcher /></li>
        </ul>
      </nav>
    </header>

    {#if isQuiet}
      <div class="quiet-status-strip" role="status" aria-live="polite">
        <span class="quiet-status-label">
          <iconify-icon icon="tabler:player-pause"></iconify-icon>
          {quietHoursActive && !manualQuiet ? L.quietHoursActive : L.quietManualActive}
        </span>
        {#if manualQuiet}
          <button type="button" class="quiet-status-resume" onclick={() => setQuietMode(false)}>
            {L.quietResume}
          </button>
        {/if}
      </div>
    {/if}

    <main class="container">{@render children()}</main>

    <footer class="container">
      <small class="footer-text">{L.tagline}</small>
    </footer>
  </div>

  <nav class="bottom-nav" aria-label={L.bottomNav}>
    <button
      class="bottom-nav-btn {isActive('/') ? 'active' : ''}"
      onclick={handleHomeClick}
      title={L.home}
      aria-label={L.home}
      type="button"
    >
      <iconify-icon icon="tabler:home"></iconify-icon>
    </button>
    <button
      class="bottom-nav-btn {isActive('/inbox') ? 'active' : ''}"
      onclick={() => navigate('/inbox')}
      title={L.inbox}
      aria-label={L.inbox}
      type="button"
    >
      <span class="bottom-nav-bell-wrapper">
        <iconify-icon icon="tabler:inbox"></iconify-icon>
        {#if inboxUnread > 0}
          <span class="notification-badge">{inboxUnread > 99 ? '99+' : inboxUnread}</span>
        {/if}
      </span>
    </button>
    <button
      class="bottom-nav-btn {isActive('/settings') ? 'active' : ''}"
      onclick={() => navigate('/settings')}
      title={L.settings}
      aria-label={L.settings}
      type="button"
    >
      <iconify-icon icon="tabler:settings"></iconify-icon>
    </button>
  </nav>

  <button
    class="note-fab"
    type="button"
    onclick={() => { showCompose = true }}
    title={L.composeTitle}
    aria-label={L.composeTitle}
  >
    <iconify-icon icon="tabler:pencil-plus"></iconify-icon>
  </button>

  {#if showCompose}
    <div
      class="compose-overlay"
      role="presentation"
      onclick={closeComposeOnBackdrop}
    >
      <div
        class="compose-modal"
        role="dialog"
        aria-modal="true"
        aria-labelledby="compose-modal-title"
        use:focusTrap
      >
        <div class="compose-modal-header">
          <span id="compose-modal-title" class="compose-modal-title">{L.composeTitle}</span>
          <button
            type="button"
            class="compose-close-btn"
            onclick={() => { showCompose = false }}
            aria-label={L.actionClose}
          >
            <iconify-icon icon="tabler:x"></iconify-icon>
          </button>
        </div>
        <PostForm onPosted={() => { showCompose = false }} />
      </div>
    </div>
  {/if}
</div>

// packages/kaguya-app/src/ui/Layout.tsx
// SPDX-License-Identifier: MPL-2.0

import { useState, useEffect } from 'preact/hooks'
import { Link, useLocation } from './router'
import type { ComponentChildren } from 'preact'
import { instanceName } from '../domain/auth/appState'
import { unreadCount, inboxCount, initInbox } from '../domain/notification/notificationStore'
import { initFilteredTimeline } from '../domain/timeline/filteredTimelineStore'
import { init as themeInit, toggle as themeToggle, isDark, currentTheme } from './themeStore'
import { init as preferencesInit, quietMode, isQuiet as isQuietSignal, isQuietHoursActive, setQuietMode, toggleQuietMode } from './preferencesStore'
import { init as mediaProxyInit } from '../infra/mediaProxy'
import { init as i18nInit, t, currentLocale } from '../infra/i18n'
import { AccountSwitcher } from '../domain/account/AccountSwitcher'
import { PostForm } from './PostForm'

type Props = {
  children: ComponentChildren
}

export function Layout({ children }: Props) {
  const instName = instanceName.value
  const notifCount = unreadCount.value
  const inboxUnread = inboxCount.value
  const [location, navigate] = useLocation()
  const [showCompose, setShowCompose] = useState(false)

  useEffect(() => {
    i18nInit()
    themeInit()
    preferencesInit()
    mediaProxyInit()
    initInbox()
    initFilteredTimeline()
  }, [])

  // Subscribe to signals for re-rendering
  const _theme = currentTheme.value
  const _locale = currentLocale.value
  const darkMode = isDark()
  const manualQuiet = quietMode.value
  const quietHoursActive = isQuietHoursActive.value
  const isQuiet = isQuietSignal.value

  function isActive(path: string) { return location === path }

  function handleBack() {
    if (history.length > 1) history.back()
    else navigate('/')
  }

  function scrollMainToTop() {
    const main = document.querySelector<HTMLElement>('.layout-main > main')
    if (main) main.scrollTo({ top: 0, behavior: 'smooth' })
    else window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  // Home buttons double as "scroll to top" when already on /.
  // The scroll also brings the top-sentinel into view, which auto-flushes
  // any pending streamed notes — matches the pill-tap behavior for free.
  function handleHomeClick() {
    if (location === '/') scrollMainToTop()
    else navigate('/')
  }

  const isRootPage = location === '/' || location === '/notifications' || location === '/inbox'
    || location === '/timeline-inbox' || location === '/settings' || location === '/performance'
    || location === '/miauth-callback' || location.startsWith('/oauth-callback')

  return (
    <div class="layout">
      <nav class="left-sidebar" aria-label={t('nav.side_navigation')}>
        <Link href="/" class="sidebar-logo">
          <div class="sidebar-logo-icon">🌿</div>
        </Link>
        <div class="sidebar-nav-items">
          <button class={`sidebar-nav-btn${isActive('/') ? ' active' : ''}`} onClick={handleHomeClick} title={t('nav.home')} aria-label={t('nav.home')} type="button">
            <iconify-icon icon="tabler:home" />
          </button>
          <button class={`sidebar-nav-btn${isActive('/inbox') ? ' active' : ''}`} onClick={() => navigate('/inbox')} title={t('nav.inbox')} aria-label={t('nav.inbox')} type="button">
            <iconify-icon icon="tabler:inbox" />
            {inboxUnread > 0 && <span class="sidebar-notification-badge">{inboxUnread > 99 ? '99+' : inboxUnread}</span>}
          </button>
          <button class={`sidebar-nav-btn${isActive('/notifications') ? ' active' : ''}`} onClick={() => navigate('/notifications')} title={t('nav.notifications')} aria-label={t('nav.notifications')} type="button">
            <iconify-icon icon="tabler:bell" />
            {notifCount > 0 && <span class="sidebar-notification-badge">{notifCount > 99 ? '99+' : notifCount}</span>}
          </button>
        </div>
        <div class="sidebar-bottom">
          <button class="sidebar-nav-btn" onClick={toggleQuietMode}
            title={manualQuiet ? t('quiet_mode.off') : t('quiet_mode.on')}
            aria-label={manualQuiet ? t('quiet_mode.off') : t('quiet_mode.on')}
            aria-pressed={isQuiet} type="button">
            <iconify-icon icon={isQuiet ? 'tabler:player-play' : 'tabler:player-pause'} />
          </button>
          <button class="sidebar-nav-btn theme-toggle-sidebar" onClick={themeToggle}
            title={darkMode ? t('theme.switch_to_light') : t('theme.switch_to_dark')}
            aria-label={darkMode ? t('theme.switch_to_light') : t('theme.switch_to_dark')} type="button">
            <iconify-icon icon={darkMode ? 'tabler:sun' : 'tabler:moon'} />
          </button>
          <button class={`sidebar-nav-btn${isActive('/settings') ? ' active' : ''}`} onClick={() => navigate('/settings')} title={t('nav.settings')} aria-label={t('nav.settings')} type="button">
            <iconify-icon icon="tabler:settings" />
          </button>
        </div>
      </nav>

      <div class="layout-main">
        <header class="container-fluid">
          <nav>
            <ul>
              <li>
                {!isRootPage && (
                  <button class="header-back-btn" onClick={handleBack} title={t('nav.back')} aria-label={t('nav.back')} type="button">
                    <iconify-icon icon="tabler:arrow-left" />
                  </button>
                )}
                <Link href="/" class="header-logo-link" onClick={() => { if (location === '/') scrollMainToTop() }}>
                  <span class="header-leaf-icon">🌿</span>
                </Link>
                <strong class="app-title">{t('app.title')}</strong>
                {instName && <small class="instance-badge">{instName}</small>}
              </li>
            </ul>
            <ul>
              <li><Link href="/" class={`header-nav-link${isActive('/') ? ' active' : ''}`} onClick={() => { if (location === '/') scrollMainToTop() }}>{t('nav.home')}</Link></li>
              <li>
                <Link href="/notifications" class={`notification-bell header-nav-link${isActive('/notifications') ? ' active' : ''}`}>
                  🔔
                  {notifCount > 0 && <span class="notification-badge">{notifCount > 99 ? '99+' : notifCount}</span>}
                </Link>
              </li>
            </ul>
            <ul>
              <li>
                <button class="theme-toggle-btn" onClick={themeToggle}
                  title={darkMode ? t('theme.switch_to_light') : t('theme.switch_to_dark')}
                  aria-label={darkMode ? t('theme.switch_to_light') : t('theme.switch_to_dark')} type="button">
                  <iconify-icon icon={darkMode ? 'tabler:sun' : 'tabler:moon'} />
                </button>
              </li>
              <li><AccountSwitcher /></li>
            </ul>
          </nav>
        </header>
        {isQuiet && (
          <div class="quiet-status-strip" role="status" aria-live="polite">
            <span class="quiet-status-label">
              <iconify-icon icon="tabler:player-pause" />
              {quietHoursActive && !manualQuiet ? t('quiet_mode.hours_active') : t('quiet_mode.manual_active')}
            </span>
            {manualQuiet && (
              <button type="button" class="quiet-status-resume" onClick={() => setQuietMode(false)}>
                {t('quiet_mode.resume')}
              </button>
            )}
          </div>
        )}
        <main class="container">{children}</main>
        <footer class="container">
          <small class="footer-text">{t('app.tagline')}</small>
        </footer>
      </div>

      <nav class="bottom-nav" aria-label={t('nav.bottom_navigation')}>
        <button class={`bottom-nav-btn${isActive('/') ? ' active' : ''}`} onClick={handleHomeClick} title={t('nav.home')} aria-label={t('nav.home')} type="button">
          <iconify-icon icon="tabler:home" />
        </button>
        <button class={`bottom-nav-btn${isActive('/inbox') ? ' active' : ''}`} onClick={() => navigate('/inbox')} title={t('nav.inbox')} aria-label={t('nav.inbox')} type="button">
          <span class="bottom-nav-bell-wrapper">
            <iconify-icon icon="tabler:inbox" />
            {inboxUnread > 0 && <span class="notification-badge">{inboxUnread > 99 ? '99+' : inboxUnread}</span>}
          </span>
        </button>
        <button class={`bottom-nav-btn${isActive('/settings') ? ' active' : ''}`} onClick={() => navigate('/settings')} title={t('nav.settings')} aria-label={t('nav.settings')} type="button">
          <iconify-icon icon="tabler:settings" />
        </button>
      </nav>

      <button class="note-fab" type="button" onClick={() => setShowCompose(true)} title={t('compose.title')} aria-label={t('compose.title')}>
        <iconify-icon icon="tabler:pencil-plus" />
      </button>

      {showCompose && (
        <div class="compose-overlay" onClick={e => { if (e.target === e.currentTarget) setShowCompose(false) }}>
          <div class="compose-modal">
            <div class="compose-modal-header">
              <span class="compose-modal-title">{t('compose.title')}</span>
              <button type="button" class="compose-close-btn" onClick={() => setShowCompose(false)} aria-label={t('action.close')}>
                <iconify-icon icon="tabler:x" />
              </button>
            </div>
            <PostForm onPosted={() => setShowCompose(false)} />
          </div>
        </div>
      )}
    </div>
  )
}
