// packages/kaguya-app/src/ui/Toast.tsx
// SPDX-License-Identifier: MPL-2.0

import { toasts, dismissToast, type Toast } from './toastState'
import { t } from '../infra/i18n'

const iconMap = {
  error: '❌',
  warning: '⚠️',
  info: 'ℹ️',
  success: '✓',
}

type ToastItemProps = {
  toast: Toast
  onDismiss: () => void
}

function ToastItem({ toast, onDismiss }: ToastItemProps) {
  const icon = iconMap[toast.type_]

  return (
    <div
      className="toast-item"
      data-type={toast.type_}
      role="alert"
      aria-live="assertive"
    >
      <span className="toast-icon" aria-hidden="true">{icon}</span>
      <div className="toast-content">
        {toast.message}
        {toast.action && (
          <div>
            <button
              className="toast-action-btn"
              onClick={() => toast.action!.onClick()}
              type="button"
            >
              {toast.action.label}
            </button>
          </div>
        )}
      </div>
      <button
        className="toast-close-btn"
        onClick={onDismiss}
        aria-label={t('notifications.close')}
        type="button"
      >
        ×
      </button>
    </div>
  )
}

export function Toast() {
  const currentToasts = toasts.value
  if (currentToasts.length === 0) return null

  return (
    <div className="toast-container" aria-live="polite">
      <div className="toast-inner">
        {currentToasts.map(toast => (
          <ToastItem key={toast.id} toast={toast} onDismiss={() => dismissToast(toast.id)} />
        ))}
      </div>
    </div>
  )
}

// packages/kaguya-app/src/ui/Toast.svelte
<!--
  SPDX-License-Identifier: MPL-2.0

  Svelte port of Toast.tsx. Not yet mounted at runtime — Toast.tsx
  remains the live root component until M1 mount swap.
-->

<script lang="ts">
  import { toasts, dismissToast, type ToastType } from './toastState'
  import { currentLocale, t } from '../infra/i18n'
  import { svelteSignal } from './svelteSignal.svelte'

  const toastsR = svelteSignal(toasts)
  const localeR = svelteSignal(currentLocale)

  const iconMap: Record<ToastType, string> = {
    error: '❌',
    warning: '⚠️',
    info: 'ℹ️',
    success: '✓',
  }

  // Tie `t()` re-evaluation to locale changes (comma operator).
  const closeLabel = $derived((localeR.value, t('notifications.close')))
</script>

{#if toastsR.value.length > 0}
  <div class="toast-container" aria-live="polite">
    <div class="toast-inner">
      {#each toastsR.value as toast (toast.id)}
        <div
          class="toast-item"
          data-type={toast.type_}
          role="alert"
          aria-live="assertive"
        >
          <span class="toast-icon" aria-hidden="true">{iconMap[toast.type_]}</span>
          <div class="toast-content">
            {toast.message}
            {#if toast.action}
              <div>
                <button
                  class="toast-action-btn"
                  type="button"
                  onclick={() => toast.action!.onClick()}
                >
                  {toast.action.label}
                </button>
              </div>
            {/if}
          </div>
          <button
            class="toast-close-btn"
            type="button"
            aria-label={closeLabel}
            onclick={() => dismissToast(toast.id)}
          >
            ×
          </button>
        </div>
      {/each}
    </div>
  </div>
{/if}
